apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: mysql-secret
  namespace: project-staging

spec:

  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: mysql-secret

  data:

  - secretKey: username
    remoteRef:
      key: cloud-native-project-mysql-secret
      property: username

  - secretKey: password
    remoteRef:
      key: cloud-native-project-mysql-secret
      property: password

  - secretKey: host
    remoteRef:
      key: cloud-native-project-mysql-secret
      property: host

  - secretKey: database
    remoteRef:
      key: cloud-native-project-mysql-secret
      property: database